<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_RetourEfficace" Id="{c14c33d8-dbee-4249-b7b2-87313a39a468}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FB_RetourEfficace
VAR_INPUT
Ir_PosX : BOOL ;
Ir_PosY : BOOL ;	
Ir_PosXVoulue : BOOL ;	
Ir_PosYVoulue : BOOL ;	
END_VAR
VAR_OUTPUT
	
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF Ir_PosX ]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>